all:
  children:
    test_servers:
      hosts:
        ubuntu_test_server:
          ansible_host: "{{ test_server_ip | default('192.168.1.100') }}"
          ansible_user: "{{ test_server_user | default('ubuntu') }}"
          ansible_ssh_private_key_file: "{{ ssh_key_path | default('~/.ssh/id_rsa') }}"
          ansible_python_interpreter: /usr/bin/python3
      vars:
        # URLs dos serviços (ajustar conforme ambiente)
        app_url: "http://{{ ansible_host }}:8080"
        frontend_url: "http://{{ ansible_host }}:5173"
        keycloak_url: "http://{{ ansible_host }}:8180"
        
        # Configurações do Keycloak
        keycloak_realm: "durvalcrm"
        keycloak_client_id: "durvalcrm-frontend"
        keycloak_admin: "admin"
        keycloak_admin_password: "admin"
        
        # Token de admin (será preenchido dinamicamente)
        keycloak_admin_token: "{{ lookup('pipe', '../scripts/get_keycloak_admin_token.sh') }}"