version: '3.8'

services:
  # Serviço do Banco de Dados PostgreSQL (sem alterações)
  postgres-db:
    image: docker.io/library/postgres:15-alpine
    container_name: durvalcrm_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: durvalcrm_user
      POSTGRES_PASSWORD: durvaldev@123 # Troque por uma senha segura
      POSTGRES_DB: durvalcrm_dev
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
    networks:
      - durvalcrm-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U durvalcrm_user -d durvalcrm_dev"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # Serviço do Keycloak com Healthcheck
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: durvalcrm_keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HTTP_ENABLED=true
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
    command: start-dev --import-realm --health-enabled=true --metrics-enabled=true
    ports:
      - "8080:8080"
      - "8443:8443"
      - "9000:9000"
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./keycloak/themes:/opt/keycloak/themes
      - ./realm-durvalcrm.json:/opt/keycloak/data/import/realm-durvalcrm.json
    networks:
      - durvalcrm-net
    # Removido healthcheck temporariamente - verificar manualmente

  # API Backend - DurvalCRM
  durvalcrm-api:
    image: docker.io/rafestevam/durvalcrm-api:latest
    container_name: durvalcrm_api
    environment:
      - DB_USER=durvalcrm_user
      - DB_PASSWORD=durvaldev@123 # Troque por uma senha segura
      - DB_NAME=durvalcrm_dev
      - DB_URL=jdbc:postgresql://postgres-db:5432/durvalcrm_dev
      - KEYCLOAK_URL=http://localhost:8080
      - KEYCLOAK_CLIENT_ID=durvalcrm-client
    ports:
      - "8082:8082"
    networks:
      - durvalcrm-net
    depends_on:
      - postgres-db
      - keycloak

  # Frontend - DurvalCRM
  durvalcrm-frontend:
    image: docker.io/rafestevam/durvalcrm-frontend:latest
    container_name: durvalcrm_frontend
    ports:
      - "3000:3000"
    depends_on:
      - keycloak
      - durvalcrm-api
networks:
  durvalcrm-net:
    driver: bridge
volumes:
  pgdata:
    driver: local
  keycloak_data:
    driver: local